# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

#############################################################################################
      - uses: conda-incubator/setup-miniconda@v1.7.0
        with:
          activate-environment: pulsequantum
          environment-file: ./environment.yml
          #python-version: 3.5
          #condarc-file: etc/example-condarc.yml
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda update -n base -c defaults conda
          conda info
          conda list
      - name: disable_telemetry
        run: sed -i "s/\(enabled *= *\).*/\1False/" ./pulsequantum/conf/telemetry.ini
        shell: bash -l {0}
  ###############################################################################################
      - shell: bash -l {0} 
        name: mypy
        run: |
          conda info
          conda list
          #source activate pulsequantum &&
          #mypy pulsequantum --junit-xml test-mypy-results.xml
    #  displayName: mypy
    #- bash: | # needs --cov= to generate Report
     #   source activate pulsequantum &&
      #  pytest --junitxml=test-results.xml --cov=pulsequantum --cov-report=xml --cov-config=.coveragerc pulsequantum
      #displayName: Run the tests
      #condition: succeededOrFailed():

